apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector: 
    app: first-app-declarative
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-declarative
  labels:
    group: example
spec:
  replicas: 1
  selector: 
    # matchLabels:
    #    app: first-app-declarative
    #    tier: backend
    matchExpressions:
      - { key: app, operator: In, values: [first-app-declarative]}
      - { key: tier, operator: In, values: [backend]}
  template:
    metadata:
      labels:
        app: first-app-declarative
        tier: backend
    spec: 
      containers:
        - name: declarative-node
          image: kumudug/kub-first-app
          livenessProbe: 
            httpGet: 
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10